# syntax = docker/dockerfile:experimental
FROM ubuntu:22.04 as buildtemp
WORKDIR /tmp
COPY . ./

FROM ubuntu:22.04

ARG ASCEND_BASE=/usr/local/Ascend
WORKDIR /home/AscendWork

# 安装系统依赖
RUN sed -i "s@http://.*ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list && \
    apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends gcc g++ make cmake zlib1g zlib1g-dev openssl libsqlite3-dev libssl-dev \
    libffi-dev unzip pciutils net-tools libblas-dev gfortran libblas3 curl && \
    apt clean && rm -rf /var/lib/apt/lists/*
 
ENV LD_LIBRARY_PATH=/usr/local/python3.9.2/lib:$LD_LIBRARY_PATH
ENV PATH=/usr/local/python3.9.2/bin:$PATH

# 推理程序需要使用到底层驱动，底层驱动的运行依赖HwHiAiUser，HwBaseUser，HwDmUser三个用户
# 创建运行推理应用的用户及组，HwHiAiUse，HwDmUser，HwBaseUser的UID与GID分别为1000，1101，1102为例
RUN umask 0022 && \
    groupadd  HwHiAiUser -g 1000 && \
    useradd -d /home/HwHiAiUser -u 1000 -g 1000 -m -s /bin/bash HwHiAiUser && \
    groupadd HwDmUser -g 1101 && \
    useradd -d /home/HwDmUser -u 1101 -g 1101 -m -s /bin/bash HwDmUser && \
    usermod -aG HwDmUser HwHiAiUser && \
    groupadd HwBaseUser -g 1102 && \
    useradd -d /home/HwBaseUser -u 1102 -g 1102 -m -s /bin/bash HwBaseUser && \
    usermod -aG HwBaseUser HwHiAiUser

# 安装python和python库
RUN umask 0022 && \
    curl -k https://repo.huaweicloud.com/python/3.9.2/Python-3.9.2.tgz -o Python-3.9.2.tgz && \
    tar -xf Python-3.9.2.tgz && cd Python-3.9.2 && ./configure --prefix=/usr/local/python3.9.2 --enable-shared && \
    make -j20 && make install && \
    ln -sf /usr/local/python3.9.2/bin/python3 /usr/bin/python3 && \
    ln -sf /usr/local/python3.9.2/bin/python3 /usr/bin/python && \
    ln -sf /usr/local/python3.9.2/bin/pip3 /usr/bin/pip3 && \
    ln -sf /usr/local/python3.9.2/bin/pip3 /usr/bin/pip && \
    cd .. && \
    rm -rf Python*

# 安装python库和CANN包
RUN --mount=type=cache,target=/tmp,from=buildtemp,source=/tmp \
    cp /tmp/run.sh /home/AscendWork/ && \
    chmod +x /home/AscendWork/run.sh && \
    mkdir -p ~/.pip  && \
    echo '[global] \n\
    index-url=http://pypi.douban.com/simple\n\
    trusted-host=pypi.douban.com' >> ~/.pip/pip.conf && \
    pip3 install pip -U && \
    pip3 install -r /tmp/requirements.txt && \
    rm -rf /root/.cache/pip && \
    bash /tmp/Ascend-cann-toolkit*.run --quiet --install --install-path=$ASCEND_BASE --install-for-all --force && \
    chown -R HwHiAiUser:HwHiAiUser /home/AscendWork/ && \
    ln -sf /lib /lib64 && \
    mkdir /var/dmp && \
    mkdir /usr/slog && \
    chown HwHiAiUser:HwHiAiUser /usr/slog && \
    chown HwHiAiUser:HwHiAiUser /var/dmp

ENV LD_PRELOAD=/lib/aarch64-linux-gnu/libc.so.6
ENV ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ENV TOOLCHAIN_HOME=${ASCEND_TOOLKIT_HOME}/toolkit
ENV PYTHONPATH=${ASCEND_TOOLKIT_HOME}/python/site-packages:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe
ENV ASCEND_AICPU_PATH=${ASCEND_TOOLKIT_HOME}
ENV ASCEND_OPP_PATH=${ASCEND_TOOLKIT_HOME}/opp
ENV ASCEND_HOME_PATH=${ASCEND_TOOLKIT_HOME}
ENV LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${ASCEND_TOOLKIT_HOME}/lib64/plugin/opskernel:${ASCEND_TOOLKIT_HOME}/lib64/plugin/nnengine:/usr/local/python3.9.2/lib:/usr/local/Ascend/driver/lib64:/usr/lib64
ENV PATH=${ASCEND_TOOLKIT_HOME}/bin:${ASCEND_TOOLKIT_HOME}/compiler/ccec_compiler:/usr/local/python3.9.2/bin:$PATH


USER 1000
CMD bash /home/AscendWork/run.sh